spring.application.name=gogame
spring.datasource.url=jdbc:mysql://localhost:3306/gogame-database
spring.datasource.username= fzlcentral
spring.datasource.password= Established514*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
server.port=8080
server.ssl.enabled=false